services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-app
    ports:
      - "5000:5000"
    volumes:
      # Montaje de volumen local para "Hot Reload" (sincronización de código en tiempo real)
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    # Se añade la bandera --reload a Gunicorn para reiniciar los procesos al detectar cambios en archivos Python
    command: sh -c "gunicorn --reload --bind 0.0.0.0:${PORT:-5000} app:app"
